feat: JavaScript Weekly #571 feat: JavaScript Weekly #554 补充空白文
FEDarling/weekly-tracker pull request #139
Opened 2022-02-15 02:10 UTC by chressYu

2022-02-15 03:20 UTC, daodaolee reviewed
麻烦根据规范过一下，看到有很多英文逗号，还有部分地方没有空格，下面的译者可以填写成你的github链接格式

2022-02-17 12:18 UTC, KimYangOfCat requested changes

2022-02-17 12:18 UTC, KimYangOfCat commented on weeklys/javascript_weekly/571/Is_It_Time_for_the_JavaScript_Temporal_API.md
>  title: 'Is It Time for the JavaScript Temporal API?'
标题也得翻译一下，辛苦啦！

2022-02-20 13:24 UTC, KimYangOfCat approved these changes

2022-02-20 13:24 UTC, KimYangOfCat commented on weeklys/javascript_weekly/571/Is_It_Time_for_the_JavaScript_Temporal_API.md
> +title: '是时候开始使用JavaScript Temporal API了'
```suggestion
title: '是开始使用 JavaScript Temporal API 的时候了吗？'
```

2022-02-20 13:33 UTC, merged